import 'dart:math' as math;
import 'dart:ui' show Color;

/// A colour in the OKLCH perceptual colour space (CLAUDE.md §11.4).
///
/// Why not hex: equal numeric steps in OKLCH lightness produce equal
/// *perceived* steps at every hue, so a tonal ramp can be generated by holding
/// hue and chroma fixed and stepping [l]. HSL does not have that property — a
/// ramp built there drifts in both brightness and hue, which is why hand-tuned
/// palettes rarely look coherent next to each other.
///
/// This is what makes eight palettes (four themes x light/dark) tractable:
/// dark mode is the same hue and chroma at inverted lightness, not a second
/// set of hand-picked values.
class Oklch {
  const Oklch(this.l, this.c, this.h);

  /// Perceptual lightness, 0 (black) to 1 (white).
  final double l;

  /// Chroma — 0 is grey, ~0.37 is the most saturated sRGB can hold.
  final double c;

  /// Hue angle in degrees, 0-360.
  final double h;

  /// Same hue and chroma at a different lightness — the tonal-ramp operation.
  Oklch withL(double newL) => Oklch(newL, c, h);

  /// Same hue and lightness, less saturated. Dark surfaces need lower chroma:
  /// a chroma that reads as vivid on white glares on near-black (§11.5.10).
  Oklch withC(double newC) => Oklch(l, newC, h);

  Oklch lighten(double amount) => withL((l + amount).clamp(0.0, 1.0));
  Oklch darken(double amount) => withL((l - amount).clamp(0.0, 1.0));

  /// Converts to a display colour, clamping into the sRGB gamut.
  ///
  /// OKLCH -> OKLab -> LMS -> linear sRGB -> gamma-encoded sRGB, per the
  /// CSS Color Level 4 definition of `oklch()`.
  Color toColor({double opacity = 1.0}) {
    final hRad = h * math.pi / 180.0;
    final a = c * math.cos(hRad);
    final b = c * math.sin(hRad);

    // OKLab to non-linear LMS.
    final lp = l + 0.3963377774 * a + 0.2158037573 * b;
    final mp = l - 0.1055613458 * a - 0.0638541728 * b;
    final sp = l - 0.0894841775 * a - 1.2914855480 * b;

    final lm = lp * lp * lp;
    final mm = mp * mp * mp;
    final sm = sp * sp * sp;

    final red = 4.0767416621 * lm - 3.3077115913 * mm + 0.2309699292 * sm;
    final green = -1.2684380046 * lm + 2.6097574011 * mm - 0.3413193965 * sm;
    final blue = -0.0041960863 * lm - 0.7034186147 * mm + 1.7076147010 * sm;

    return Color.fromARGB(
      (opacity.clamp(0.0, 1.0) * 255).round(),
      _encode(red),
      _encode(green),
      _encode(blue),
    );
  }

  /// Linear light to an 8-bit sRGB channel. Out-of-gamut values clamp, which
  /// is why very high chroma flattens rather than wrapping to a wrong hue.
  static int _encode(double linear) {
    final v = linear <= 0.0031308
        ? 12.92 * linear
        : 1.055 * math.pow(linear, 1 / 2.4) - 0.055;
    return (v.clamp(0.0, 1.0) * 255).round();
  }

  @override
  String toString() => 'oklch(${l.toStringAsFixed(3)} '
      '${c.toStringAsFixed(3)} ${h.toStringAsFixed(1)})';
}

/// WCAG 2.x relative luminance of an sRGB colour.
double relativeLuminance(Color color) {
  double channel(int v) {
    final s = v / 255.0;
    return s <= 0.03928 ? s / 12.92 : math.pow((s + 0.055) / 1.055, 2.4) * 1.0;
  }

  return 0.2126 * channel((color.r * 255).round()) +
      0.7152 * channel((color.g * 255).round()) +
      0.0722 * channel((color.b * 255).round());
}

/// WCAG contrast ratio between two opaque colours, 1.0 (identical) to 21.0
/// (black on white). AA wants >= 4.5 for body text and >= 3.0 for large text
/// and meaningful UI boundaries (CLAUDE.md §12.2).
double contrastRatio(Color a, Color b) {
  final la = relativeLuminance(a);
  final lb = relativeLuminance(b);
  final lighter = math.max(la, lb);
  final darker = math.min(la, lb);
  return (lighter + 0.05) / (darker + 0.05);
}

/// Picks whichever of [candidates] reads most clearly on [background].
///
/// Deriving "text on this fill" instead of hand-picking it is what keeps
/// category-coloured surfaces accessible: a fill can be retuned without
/// silently dropping its label below AA.
Color mostReadableOn(Color background, List<Color> candidates) {
  var best = candidates.first;
  var bestRatio = 0.0;
  for (final candidate in candidates) {
    final ratio = contrastRatio(background, candidate);
    if (ratio > bestRatio) {
      bestRatio = ratio;
      best = candidate;
    }
  }
  return best;
}
